# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  hermesidentity:
    image: hermesidentity
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - 8001
